[package]
edition = "2018"
name = "linkmetest"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
cortex-m-semihosting = "0.3.3"
panic-semihosting = { version = "0.5.0", features = ["exit"] }
linkme = "^0.1.4"
